from typing import List

# Shared constants for Glue jobs
RAW_REDDIT_DATA_BUCKET_NAME = "shopping-assistant-raw-reddit-data"
PROCESSED_REDDIT_DATA_BUCKET_NAME = "shopping-assistant-processed-reddit-data"
GLUE_DATABASE_NAME = "reddit_data"
GLUE_TABLE_NAME = "reddit_data_table"

SUBREDDIT_NAMES: List[str] = [
    "buyitforlife",
    "gadgets",
    "frugal",
    "suggestalaptop",
    "whatisthisthing",
    "deals",
    "buildapcsales",
    "gamedeals",
    "personalfinance",
    "shutupandtakemymoney",
    "cooking",
    "beauty",
    "homeimprovement",
    "productivity",
    "backpacks",
    "malefashionadvice",
    "frugalmalefashion",
    "femalefashionadvice",
    "goodvalue",
    "thriftstorehauls",
    "homeautomation",
    "smarthome",
    "edc",  # Everyday Carry
    "coffee",
    "headphones",
    "gaming",
    "gamingdeals",
    "shutupandtakemymoney",
    "frugalliving",
    "zerowaste",
    "minimalism",
    "techsupport",
    "android",
    "ios",
    "apple",
    "diy",
    "interiordesign",
    "mealprepsunday",
    "travelhacks",
    "askhistorians",
    "skincareaddiction",
    "rawdenim",
    "askreddit",
    "askmenover30",
    "askwomenover30",
    "askmen",
    "askwomen",
    "askreddit",
    "jacquesmariemage",
    "sunglasses",
    "GiftIdeas",
    "perfectgift",
    "HelpMeFind",
]
